### ISSUE TITLE
Problem with volume mount 

### ISSUE THREAD

**Issue by stepan-romankov** [Graylog2/graylog2-images#142]
Sometimes container can't be recreated with error:
`
ERROR: for graylog  Invalid bind mount spec "32d46005b428f92cf93d942014b261073f097f5b4cc9d370f612c4a2a3a07b35:data:rw": Invalid volume destination path: 'data' mount path must be absolute.
`

Potentially due to line 52 in Dockerfile:
`
VOLUME ./data
`

**Comment by mariussturm** [comment]
What does 'sometimes' mean?
How exactly do you start the container? How does the volume options look like?

**Comment by stepan-romankov** [comment]
Hi, I have following docker-compose configuration. If I change options in grayling container then next time after docker-compose up -d "Recreation" will fail. I assume this is because relative volume path in Dockerfile ("./data"). 

```
some-mongo:
  image: "mongo:3"
  volumes:
    -  /opt/docker/mongo:/data/db
elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
  volumes:
    - /opt/docker/elasticsearch/data:/usr/share/elasticsearch/data
grayling
  image: graylog2/server:2.0.0-2
  volumes:
    - /opt/docker/graylog/data/journal:/usr/share/graylog/data/journal
    - /opt/docker/graylog/data/plugin:/usr/share/graylog/data/plugin
    - /opt/docker/graylog/data/log:/usr/share/graylog/data/log
    - ./config:/usr/share/graylog/data/config
  environment:
    GRAYLOG_PASSWORD_SECRET: {some phrase}
    GRAYLOG_ROOT_PASSWORD_SHA2: {some sha2}
    GRAYLOG_REST_LISTEN_URI: http://0.0.0.0:12900/
    GRAYLOG_REST_TRANSPORT_URI: http://{real ip address}:12900/

  links:
    - some-mongo:mongo
    - elasticsearch:elasticsearch
  ports:
    - "9000:9000"
    - "12900:12900"

```
