### ISSUE TITLE
Many errors with docker-compose example: An I/O error has occurred while writing a response message entity to the container output stream.

### ISSUE THREAD

**Issue by harobed** [Graylog2/graylog2-images#160]
Hi,

I use `docker-compose.yml` documented here: http://docs.graylog.org/en/latest/pages/installation/docker.html#settings

```
some-mongo:
  image: "mongo:3"
some-elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
graylog:
  image: graylog2/server:2.0.0-1
  environment:
    GRAYLOG_PASSWORD_SECRET: somepasswordpepper
    GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    GRAYLOG_REST_TRANSPORT_URI: http://127.0.0.1:12900
  links:
    - some-mongo:mongo
    - some-elasticsearch:elasticsearch
  ports:
    - "9000:9000"
    - "12900:12900"
```

and I've many error in log (`docker-compose up`):

https://gist.github.com/harobed/42a94ddf7c231bf0d20a91fd4543f79e

Is it a bug in Official Graylog Docker Image ?
