### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by nmiculinic** [Graylog2/graylog2-images#198]
I'm trying to setup simple graylog with docker-compose. My docker-compose.yml is similar to yours:
```yaml
version: '2'
services:
  some-mongo:
    image: "mongo:3"
  some-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog:
    image: graylog2/server:2.1.1-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - some-mongo:mongo
      - some-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
```

And I have configured udp input: https://i.imgur.com/gaU0AG6.png  on the graylog web. However when I test with netcat to push data into graylog, I get connection refused:

```bash
echo -e '{"version": "1.1","host":"example.org","short_message":"Short message","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}\0' | nc -w 1 -u 127.0.0.1 12201
```

```read(net): Connection refused```
