### ISSUE TITLE
boot stuck on appliance

### ISSUE THREAD

**Issue by jwaibel** [Graylog2/graylog2-images#89]
I just imported the "Stable branch (1.2.0): graylog.ova" appliance into a virtualbox (5.0.4) VM.
The bootprocess hangs on the execution of the open-vm-tools init script. I had to manual login the box with ssh and kill the process. After that the boot process finished without further issues.
To avoid to get stuck again on a reboot i had to remove the package "open-vm-tools" from the system.

I only could reproduce the problem on a Centos 7 Host with VirtualBox 5.0.4 so far.

**Comment by FDiskas** [comment]
Probably the same issue. Here is my **docker-compose.yml**
```yml
graylog:
    container_name: graylog
    image: graylog2/allinone
    ports:
        - "9000:9000"
        - "12201:12201"
```
